### PR TITLE
small fixes and comments

### PR DESCRIPTION
**Pull request by amloren1**
- WRF_CRF iterator is fixed in this version
- I added comments and altered the outputs to screen. The extra verbosity is just for while we are still in devel.

### CODE REVIEW

**Comment by CaymanUnterborn** [comment]
You can't commit your own new gitignore. Can you get rid of those changes? Just revert the one file

**Comment by amloren1** [comment]
had to make two more commits. 1st for recent changes and second for .gitignore.

**Comment by CaymanUnterborn** [comment]
What's this mundo stuff?

**Comment by amloren1** [comment]
branch I was working on a couple weeks ago. Just needed to merge it so I
can integrate it into local changes on another computer. Should only be a
few extra files that I'll remove from the remote

**Comment by CaymanUnterborn** [comment]
Sounds good. I'll merge it and we can change things after the fact if need be.

**Pull request merged**
